### ISSUE TITLE
Информация страницы чата

### ISSUE THREAD

**Issue by AnnPkGit** [AnnPkGit/DiplomaWork#10]

**Comment by DanisimoFirst** [comment]
*Окно выбора чата*
Название чатов (групповых)
Имя пользователя (с кем ведется чат) 
Последнее сообщение в чате 
Время последнего сообщения в чате 
Прочитано ли нами сообщение (если нет - чат выделяется)
В сети ли юзер с кем есть чат  

*Окно чата лс *
Текст сообщения
Дата отправки сообщения 
Прочитано ли сообщение
Аватар собеседника 
Вложения (фото, видео)
