### ISSUE TITLE
Информация страницы настроек

### ISSUE THREAD

**Issue by AnnPkGit** [AnnPkGit/DiplomaWork#12]

**Comment by DanisimoFirst** [comment]
Тип аккаунта (открытый, закрытый)
Кто может писать сообщения 
Кто видит нахождения в сети 
Кто может добавлять пользователя в групповые чаты 
Кто видит личные данные пользователя (Пол, Почта ,Номер телефона, возраст)

Может ли пользователь видеть контент 18+ (можно изменить если пользователю больше 18, по дэфолту фолз)

Изменяемая информация: 
Пароль 
Имя
Пол 
Почта 
Номер телефона
Аватар 
Уведомления 
Тема (темная светлая)
Язык

Неизменяемая информация:
Логин 
Дата регистрации 
Возраст
