### ISSUE TITLE
Инвестигейт базы данных 

### ISSUE THREAD

**Issue by AnnPkGit** [AnnPkGit/DiplomaWork#2]

**Comment by DanisimoFirst** [comment]
1. Инициализировать ssh тоннель 
2. Открыть тоннель   
3. Отравить запрос внутри тоннеля 
4. Закрыть коннект



Пример:

(1)
// Инициализация ssh 
        public static (SshClient SshClient, uint Port) ConnectSsh(string sshHostName, string sshUserName,
            string sshPassword = null, // Данные для ssh 
            string sshKeyFile = null, string sshPassPhrase = null, int sshPort = 22, // Данные для ssh 
            string databaseServer = "localhost", int databasePort = 3306) // Имя сервера на котором лежит бд
        {

            // определение используемых методов аутентификации 
            var authenticationMethods = new List<AuthenticationMethod>();
            if (!string.IsNullOrEmpty(sshKeyFile))
            {
                authenticationMethods.Add(new PrivateKeyAuthenticationMethod(sshUserName,
                    new PrivateKeyFile(sshKeyFile, string.IsNullOrEmpty(sshPassPhrase) ? null : sshPassPhrase)));
            }

            if (!string.IsNullOrEmpty(sshPassword))
            {
                authenticationMethods.Add(new PasswordAuthenticationMethod(sshUserName, sshPassword));
            }

            // подключение к SSH-серверу
            var sshClient =
                new SshClient(new ConnectionInfo(sshHostName, sshPort, sshUserName, authenticationMethods.ToArray()));
            sshClient.Connect();

            // перенаправление локального порта на сервер базы данных через SSH-сервер
            var forwardedPort = new ForwardedPortLocal("127.0.0.1", databaseServer, (uint)databasePort);
            sshClient.AddForwardedPort(forwardedPort);
            forwardedPort.Start();

            return (sshClient, forwardedPort.BoundPort);
        }


  var (sshClient, localPort) = ConnectSsh(server, sshUserName, sshPassword);
            using (sshClient)
            {
                MySqlConnectionStringBuilder csb = new MySqlConnectionStringBuilder
                {
                    Server = "127.0.0.1",
                    Port = localPort,
                    UserID = databaseUserName,
                    Password = databasePassword,
                    Database = databaseName
                };

                using var connection = new MySqlConnection(csb.ConnectionString);
             (2)   connection.Open(); // Открыто подключение к бд 

                bool auth = false;
                string IdStr = "";

                DataSet ds = new DataSet();
                DataTable table = new DataTable();
                MySqlDataAdapter adapter = new MySqlDataAdapter();
                MySqlCommand command =
                    new MySqlCommand($"SELECT id FROM Users WHERE  login = '{Login}' AND pass = '{password}'",
                        connection);
                adapter.SelectCommand = command;
           (3)     //      MySqlDataReader reader = command.ExecuteReader();
           (4) connection.Dispose();
